version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.19
  pw-noble-development:
    docker:
      - image: mcr.microsoft.com/playwright:v1.55.0-noble
    environment:
      VITE_API_BASE_URL: https://mon.api.fr/api
      VITE_ADMIN_BASE_URL: https://prepro.eva.anlci.gouv.fr/admin

      VITE_ID_BENEFICIAIRE_EVA_ENTREPRISES: id_beneficiaire
      VITE_CODE_CAMPAGNE_EVA_ENTREPRISES: EVAETGILLES
commands:
  install_dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  restore_node_modules_cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

jobs:
  install-deps:
    executor: node-executor
    steps:
      - checkout
      - install_dependencies

  unit-test:
    executor: node-executor
    steps:
      - checkout
      - restore_node_modules_cache
      - run:
          name: Run unit tests
          command: npm run test:unit

  e2e-test:
    executor: pw-noble-development
    steps:
      - checkout
      - restore_node_modules_cache
      - run: cp .env.test .env
      - run: cat .env
      - run: npm install -D @playwright/test && npx playwright install --with-deps
      - run: npm run build
      - run: xvfb-run npx playwright test
      - store_artifacts:
          path: ./playwright-report
          destination: playwright-report-first
      - store_artifacts:
          path: /tmp/artifacts

  lint:
    executor: node-executor
    steps:
      - checkout
      - restore_node_modules_cache
      - run:
          name: Run ESLint
          command: npm run lint

workflows:
  version: 2
  eva-entreprises-workflow:
    jobs:
      - install-deps
      - unit-test:
          requires:
            - install-deps
      - e2e-test:
          requires:
            - install-deps
      - lint:
          requires:
            - install-deps
